theme: fluid  # 指定主题

language: zh-CN  # 指定语言，会影响主题显示的语言，按需修改

deploy:
  type: git
  repo: https://github.com/Xdydy/Xdydy.github.io
  # example, https://github.com/hexojs/hexojs.github.io
  branch: gh-pages